# =============================================================================
# Pub/Sub Resources Output (Hierarchical)
# =============================================================================
output "pubsub_resources" {
  description = "Complete Pub/Sub resources organized by topic, including subscriptions"
  value = {
    for topic_name, topic_config in local.topics : topic_name => {
      topic_name     = google_pubsub_topic.topics[topic_name].name
      topic_id       = google_pubsub_topic.topics[topic_name].id
      dlq_topic_name = var.enable_dead_letter ? google_pubsub_topic.dead_letter[topic_name].name : null

      subscriptions = {
        for adapter_name, adapter_config in topic_config.adapter_subscriptions :
        adapter_name => {
          name                  = google_pubsub_subscription.subscriptions["${topic_name}-${adapter_name}"].name
          id                    = google_pubsub_subscription.subscriptions["${topic_name}-${adapter_name}"].id
          service_account_email = google_service_account.adapters[adapter_name].email
          ack_deadline_seconds  = adapter_config.ack_deadline_seconds
        }
      }
    }
  }
}

# =============================================================================
# Service Account Outputs
# =============================================================================
output "sentinel_service_account" {
  description = "Sentinel GCP service account email (shared across all topics)"
  value       = google_service_account.sentinel.email
}

output "adapter_service_accounts" {
  description = "Map of adapter names to their GCP service account emails"
  value = {
    for adapter in local.unique_adapters : adapter => google_service_account.adapters[adapter].email
  }
}

# =============================================================================
# Helm Values Snippet
# =============================================================================
# Updated for hyperfleet-gcp overlay chart structure:
# - Base chart components (sentinel, landing-zone) go under "base:" prefix
# - GCP overlay components (validation-gcp) stay at root level
#
# NOTE: This template assumes each adapter (sentinel, landing-zone, validation-gcp)
# is configured for at most ONE topic. The Helm chart expects single blocks per adapter.
# If an adapter subscribes to multiple topics, only the first (alphabetically) is used.

output "helm_values_snippet" {
  description = "Snippet to add to Helm values for Workload Identity annotations and Pub/Sub configuration"
  value       = <<-EOT
# =============================================================================
# HyperFleet Helm Values for GCP with Pub/Sub
# Generated by terraform - use with charts/hyperfleet-gcp
#
# Usage:
#   helm install hyperfleet charts/hyperfleet-gcp -f <this-file> -n hyperfleet-system
# =============================================================================

# Base chart overrides (API, Sentinel, Landing Zone)
base:
  global:
    broker:
      type: googlepubsub
      googlepubsub:
        enabled: true
        projectId: "${var.project_id}"
        createTopicIfMissing: false
        createSubscriptionIfMissing: false
      rabbitmq:
        enabled: false

  # Sentinel - publishes to ${google_pubsub_topic.topics[local.first_topic_name].name}
  sentinel:
    serviceAccount:
      create: true
      name: ${var.sentinel_k8s_sa_name}
      annotations:
        iam.gke.io/gcp-service-account: ${google_service_account.sentinel.email}
    broker:
      type: googlepubsub
      topic: ${google_pubsub_topic.topics[local.first_topic_name].name}
      googlepubsub:
        projectId: ${var.project_id}
%{if local.landing_zone_topic != null~}

  # Landing Zone Adapter - subscribes to ${google_pubsub_topic.topics[local.landing_zone_topic].name}
  landing-zone:
    serviceAccount:
      create: true
      name: landing-zone-adapter
      annotations:
        iam.gke.io/gcp-service-account: ${google_service_account.adapters["landing-zone"].email}
    broker:
      type: googlepubsub
      googlepubsub:
        projectId: ${var.project_id}
        topic: ${google_pubsub_topic.topics[local.landing_zone_topic].name}
        subscription: ${google_pubsub_subscription.subscriptions["${local.landing_zone_topic}-landing-zone"].name}
%{if var.enable_dead_letter~}
        deadLetterTopic: ${google_pubsub_topic.dead_letter[local.landing_zone_topic].name}
%{endif~}
%{endif~}

  # Disable RabbitMQ when using Pub/Sub
  rabbitmq:
    enabled: false
%{if local.validation_gcp_topic != null~}

# GCP Validation Adapter (GCP overlay chart component - NOT under base:)
# Subscribes to ${google_pubsub_topic.topics[local.validation_gcp_topic].name}
validation-gcp:
  enabled: true
  serviceAccount:
    create: true
    name: validation-gcp-adapter
    annotations:
      iam.gke.io/gcp-service-account: ${google_service_account.adapters["validation-gcp"].email}
  broker:
    type: googlepubsub
    googlepubsub:
      projectId: ${var.project_id}
      topic: ${google_pubsub_topic.topics[local.validation_gcp_topic].name}
      subscription: ${google_pubsub_subscription.subscriptions["${local.validation_gcp_topic}-validation-gcp"].name}
%{if var.enable_dead_letter~}
      deadLetterTopic: ${google_pubsub_topic.dead_letter[local.validation_gcp_topic].name}
%{endif~}
%{endif~}
  EOT
}
