apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "namespace-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namespace-cleaner.labels" . | nindent 4 }}
data:
  namespace-cleaner.sh: |
    {{- .Files.Get "scripts/namespace-cleaner.sh" | nindent 4 }}
