apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namespace-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namespace-cleaner.labels" . | nindent 4 }}
