{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hyperfleet-gateway.fullname" . }}
  labels:
    {{- include "hyperfleet-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hyperfleet-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: /stats/prometheus
      interval: 30s
{{- end }}
