# Default values for Sentinel (nodepools)

sentinel:
  image:
    # make install will substitute this by data coming from terraform
    registry: CHANGE_THIS

  config:
    resourceType: nodepools
    resourceSelector: []
    hyperfleetApi:
      baseUrl: http://hyperfleet-api:8000
    messageData:
      id: "resource.id"
      kind: "resource.kind"
      href: "resource.href"
      generation: "resource.generation"
      owner_references:
        id: "resource.owner_references.id"
        href: "resource.owner_references.href"
        kind: "resource.owner_references.kind"

  broker:
    type: googlepubsub
    # make install will substitute this by data coming from terraform
    topic: CHANGE_THIS
    googlepubsub:
      # make install will substitute this by data coming from terraform
      projectId: CHANGE_THIS
    rabbitmq:
      # make install will substitute this by data coming from tf-helm-values.sh
      url: CHANGE_THIS
      exchangeType: topic
