apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-oidc.fullname" . }}
  labels:
    {{- include "mock-oidc.labels" . | nindent 4 }}
data:
  JSON_CONFIG: {{ toJson .Values.config | quote }}
